
[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7b7c7b"
blue = "0xb5dbff"
cyan = "0xdedeff"
green = "0xd0fba2"
magenta = "0xfb9cff"
red = "0xfdb7ae"
white = "0xfeffff"
yellow = "0xfefdc5"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x414d58"

[colors.normal]
black = "0x4d4e4d"
blue = "0x94c9fe"
cyan = "0xd2cafe"
green = "0xcbfb89"
magenta = "0xfb73ff"
red = "0xfc634f"
white = "0xdfe0df"
yellow = "0xfef8a2"

[colors.primary]
background = "0x0b0d0f"
foreground = "0xf8f8f2"

[colors.selection]
background = "0x414d58"
text = "0xf8f8f2"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "ResetFontSize"
key = "0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "="
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "="
mods = "Command|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "-"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "ArrowLeft"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "ArrowRight"
mods = "Alt"

[[keyboard.bindings]]
chars = """

"""
key = "NumpadEnter"

[[keyboard.bindings]]
chars = "\u001C1"
key = "1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C2"
key = "2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C3"
key = "3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C4"
key = "4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C5"
key = "5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C6"
key = "6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C7"
key = "7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C8"
key = "8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C9"
key = "9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "]"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "["
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Space"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B."
key = "."
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B*"
key = "8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "."
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = ","
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "-"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "\\"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "\\"
mods = "Alt|Shift"

[general]
live_config_reload = true

[terminal]

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 1

[selection]
semantic_escape_chars = """,│`|:"' ()[]{}<>"""

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/bash"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 2
y = 2

[keyboard]
