#!/bin/bash

# Log output:
#
# * 51c333e    (12 days)    <Gary Bernhardt>   add vim-eunuch
#
# The time massaging regexes start with ^[^<]* because that ensures that they
# only operate before the first "<". That "<" will be the beginning of the
# author name, ensuring that we don't destroy anything in the commit message
# that looks like time.
#
# The log format uses } characters between each field, and `column` is later
# used to split on them. A } in the commit subject or any other field will
# break this.

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%C(bold blue)<%an>%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR}$REFS $SUBJECT"

# This will output the log with titles only, plus colors:
#
# eb6e03f 2020-01-04 Add setting to log slow SQL queries (#341) <Author 3>
# 2c9a64d 2020-01-03 Adds wrap_delivery_in_transaction config (#340) <Author 2>
# 978d322 2020-01-02 Version 28.5.0 (#339) <Author 1>
# 652b7c6 2020-01-01 Use different time strategy v8.0.0 (#338) <Author 3>
#
# Any `Revert` or `Merge` keywords will become red.

git_log_simpler_titles() {
  git log \
    --pretty=format:'%C(yellow)%h %C(black)%ad%Creset %s %C(blue)<%an> %Creset' \
    --date=short    \
    --abbrev-commit \
    --color=always $1 \
    | sed ''/Merge/s//`printf "\035[31mMerge\033[0m"`/''   \
    | sed ''/Revert/s//`printf "\033[31mRevert\033[0m"`/'' \
    | less -rX
}

reset_from_origin() {
  export CURRENT_BRANCH=`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\\\\\\1\\/`
  echo "Discarding $CURRENT_BRANCH and using origin's content"
  git fetch origin
  git reset --hard origin/$CURRENT_BRANCH
}

show_git_head() {
    pretty_git_log -1
    git show -p --pretty="tformat:"
}

pretty_git_log() {
    git log --pretty="tformat:${FORMAT}" $* |
        # Replace (2 years ago) with (2 years)
        sed -Ee 's/(^[^<]*) ago)/\1)/' |
        # Replace (2 years, 5 months) with (2 years)
        sed -Ee 's/(^[^<]*), [[:digit:]]+ .*months?)/\1)/' |
        # Line columns up based on } delimiter
        column -s '}' -t |
        # Page only if we need to
        less -FXRS
}
