#!/bin/bash

if [ ! -d "~/.dotfiles" ]; then
  echo "Cloning git@github.com:kurko/.dotfiles.git into ~/.dotfiles"
  git git@github.com:kurko/.dotfiles.git ~/.dotfiles
fi

source ~/.dotfiles/bashrc_source

update_dotfiles
