" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

" set guifont=BitstreamVeraSansMono-Roman:h12            " Font family and font size.
set guifont=Monaco:h11            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=50 columns=146          " Window dimensions.

" Uncomment to use.
" set guioptions-=r                 " Don't show right scrollbar



