#! /bin/bash

INSTALLED_PACKAGE_LIST=$(brew list -1 --formula)
BREW_CASK_LIST=$(brew list -1 --cask)

function brew_install_if_absent() {
  echo -n "> $1: "
  export HOMEBREW_NO_AUTO_UPDATE=1
  echo $INSTALLED_PACKAGE_LIST | grep $1 &> /dev/null

  if [[ $? -eq 1 ]]
  then
    echo "brew installing... "
    brew install $1;
    echo "done."
    return 0
  else
    echo "already installed."
    return 1
  fi
}

function brew_cask_install_if_absent() {
  echo -n "> $1: "
  export HOMEBREW_NO_AUTO_UPDATE=1
  echo $BREW_CASK_LIST | grep $1 &> /dev/null

  if [[ $? -eq 1 ]]
  then
    echo "brew installing... "
    brew install cask $1
    echo "done."
    return 0
  else
    echo "already installed."
    return 1
  fi
}

function install_macos() {
  echo "> Installing applications..."

  if command -v brew >/dev/null 2>&1; then
    echo "Homebrew already installed!"
  else
    echo "Homebrew... "
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    brew update
    echo "done!"
  fi
  echo ""

  printf "> rbenv: "
  rbenv --version &> /dev/null
  if [[ $? -eq 0 ]]
  then
    printf "already installed.\n"
  else
    echo "installing with ruby-build... "
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    source ~/.bash_profile
    type rbenv
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo "done!\n"
    LAST_RUBY="$(rbenv install -l | grep -v - | tail -1)"
    echo "> Ruby ${LAST_RUBY}: installing... "
    rbenv install $LAST_RUBY
    rbenv global $LAST_RUBY
    echo "done!\n"
    echo "> bundler: installing... "
    gem install bundler
    echo "done!\n"
    ruby -v
  fi

  brew_install_if_absent wget
  brew_install_if_absent curl
  brew_install_if_absent tree
  brew_install_if_absent tmux
  brew_install_if_absent the_silver_searcher
  brew_install_if_absent postgresql
  brew services restart postgresql
  brew_install_if_absent redis
  brew services restart redis
  brew_install_if_absent bash-completion
  brew_install_if_absent coreutils
  brew_install_if_absent hub
  if [[ "$(which vim)" == "/usr/bin/vim" ]]; then
    brew install vim
  else
    echo "> vim: already installed."
  fi
  brew_install_if_absent imagemagick@6 && brew link imagemagick@6
  brew_install_if_absent pkg-config && brew unlink pkgconfig && brew link pkgconfig
  brew_install_if_absent mosh
  brew_install_if_absent ctags
  brew_install_if_absent fzf
  brew_install_if_absent node
  brew_install_if_absent yarn
  brew_install_if_absent jq
  brew_install_if_absent gh
  # Like cat, but with syntax highlighting
  brew_install_if_absent bat

  # casks
  brew tap kurko/homebrew-fonts-sanfrancisco
  brew tap homebrew/cask-fonts
  brew tap homebrew/cask-versions
  brew_cask_install_if_absent font-sanfrancisco
  brew_cask_install_if_absent font-hack
  brew_cask_install_if_absent font-inconsolata
  brew_cask_install_if_absent fliqlo
  brew_cask_install_if_absent slack
  brew_cask_install_if_absent alfred
  brew_cask_install_if_absent telegram
  brew_cask_install_if_absent firefox-developer-edition
  brew_cask_install_if_absent google-chrome
  brew_cask_install_if_absent 1password
}
