# Ctrl+j: this opens a popup with the names of the existing sessions and allows
# you to search them quickly with fzf.
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# Mouse drag auto-copies to system clipboard; keyboard selection requires 'y'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'pbcopy'
