#!/bin/bash

function pg {
  brew services start $(brew list | grep '^postgresql')
}

function pgstop {
  brew services stop $(brew list | grep '^postgresql')
}

function pgstatus {
  brew services info $(brew list | grep '^postgresql')
}
