#!/bin/bash

function bootstrap_machine() {
  echo "Installing applications:"

  if command -v brew >/dev/null 2>&1; then
    echo "Homebrew already installed!\n"
  else
    echo "Homebrew... "
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    brew update
    echo "done!\n"
  fi

  if command -v rbenv >/dev/null 2>&1; then
    echo "Rbenv already installed!\n"
    echo "Please, install Ruby manually"
  else
    echo "Rbenv & ruby-build... "
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    source ~/.bash_profile
    type rbenv
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo "done!\n"
    echo "Installing Ruby 2.1.2... "
    rbenv install 2.1.2
    rbenv global 2.1.2
    ruby -v
    echo "done!\n"
  fi
}
