#!/bin/bash

function bootstrap_machine() {
  echo "> Installing applications..."

  if command -v brew >/dev/null 2>&1; then
    echo "Homebrew already installed!"
  else
    echo "Homebrew... "
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    brew update
    echo "done!"
  fi
  echo ""

  printf "> Installing Rbenv... "
  if command -v rbenv >/dev/null 2>&1; then
    echo "Rbenv already installed!\n"
  else
    echo "Rbenv & ruby-build... "
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    source ~/.bash_profile
    type rbenv
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo "done!\n"
    LAST_RUBY="$(rbenv install -l | grep -v - | tail -1)"
    echo "> Installing Ruby ${LAST_RUBY}... "
    rbenv install $LAST_RUBY
    rbenv global $LAST_RUBY
    echo "done!\n"
  fi
  ruby -v

  echo ""
  echo "> Installing fliqlo... "
  brew cask install fliqlo
  echo "done."
}
